-- MySQL Script generated by MySQL Workbench
-- Sat Jan 16 20:18:26 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Drueckler3DDrucke
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Drueckler3DDrucke
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Drueckler3DDrucke` DEFAULT CHARACTER SET utf8 ;
USE `Drueckler3DDrucke` ;

-- -----------------------------------------------------
-- Table `Drueckler3DDrucke`.`CreditCard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Drueckler3DDrucke`.`CreditCard` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `number` VARCHAR(12) NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  `owner` VARCHAR(50) NOT NULL,
  `expiryDate` DATE NOT NULL,
  `securityCode` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `SecurityCode_UNIQUE` (`securityCode` ASC),
  UNIQUE INDEX `CardNumber_UNIQUE` (`number` ASC));


-- -----------------------------------------------------
-- Table `Drueckler3DDrucke`.`PaymentData`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Drueckler3DDrucke`.`PaymentData` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `iban` VARCHAR(22) NULL,
  `bill` BIT(1) NULL DEFAULT 0,
  `CreditCard_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_PaymentData_CreditCard1_idx` (`CreditCard_id` ASC),
  CONSTRAINT `fk_PaymentData_CreditCard1`
    FOREIGN KEY (`CreditCard_id`)
    REFERENCES `Drueckler3DDrucke`.`CreditCard` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Drueckler3DDrucke`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Drueckler3DDrucke`.`Address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `street` VARCHAR(50) NOT NULL,
  `number` VARCHAR(5) NOT NULL,
  `postalCode` VARCHAR(5) NOT NULL,
  `city` VARCHAR(70) NOT NULL,
  `country` VARCHAR(50) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Drueckler3DDrucke`.`ContactData`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Drueckler3DDrucke`.`ContactData` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `addressID` INT NULL,
  `firstName` VARCHAR(50) NOT NULL,
  `lastName` VARCHAR(50) NOT NULL,
  `phoneNumber` VARCHAR(50) NULL,
  `emailAddress` VARCHAR(50) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  UNIQUE INDEX `AddressID_UNIQUE` (`addressID` ASC),
  UNIQUE INDEX `PhoneNumber_UNIQUE` (`phoneNumber` ASC),
  UNIQUE INDEX `MailAddress_UNIQUE` (`emailAddress` ASC),
  UNIQUE INDEX `UserName_UNIQUE` (`username` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ContactData_Address1`
    FOREIGN KEY (`addressID`)
    REFERENCES `Drueckler3DDrucke`.`Address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Drueckler3DDrucke`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Drueckler3DDrucke`.`Customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `paymentID` INT NOT NULL,
  `guest` BIT(1) NOT NULL,
  `ContactData_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `PaymentID_UNIQUE` (`paymentID` ASC),
  INDEX `fk_Customer_ContactData1_idx` (`ContactData_id` ASC),
  UNIQUE INDEX `ContactID_UNIQUE` (`ContactData_id` ASC),
  CONSTRAINT `fk_Customer_PaymentData1`
    FOREIGN KEY (`paymentID`)
    REFERENCES `Drueckler3DDrucke`.`PaymentData` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customer_ContactData1`
    FOREIGN KEY (`ContactData_id`)
    REFERENCES `Drueckler3DDrucke`.`ContactData` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Drueckler3DDrucke`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Drueckler3DDrucke`.`Employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `admin` BIT(1) NOT NULL,
  `ContactData_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Employee_ContactData1_idx` (`ContactData_id` ASC),
  CONSTRAINT `fk_Employee_ContactData1`
    FOREIGN KEY (`ContactData_id`)
    REFERENCES `Drueckler3DDrucke`.`ContactData` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Drueckler3DDrucke`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Drueckler3DDrucke`.`Orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `Customer_id` INT NOT NULL,
  `price` DECIMAL(8,2) NOT NULL,
  `payed` BIT(1) NOT NULL,
  `Employee_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Orders_Customer1_idx` (`Customer_id` ASC),
  INDEX `fk_Orders_Employee1_idx` (`Employee_id` ASC),
  CONSTRAINT `fk_Orders_Customer1`
    FOREIGN KEY (`Customer_id`)
    REFERENCES `Drueckler3DDrucke`.`Customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Employee1`
    FOREIGN KEY (`Employee_id`)
    REFERENCES `Drueckler3DDrucke`.`Employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Drueckler3DDrucke`.`Filaments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Drueckler3DDrucke`.`Filaments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `fileName` VARCHAR(50) NOT NULL,
  `color` VARCHAR(50) NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  `producer` VARCHAR(50) NOT NULL,
  `pricePerGramm` DECIMAL(8,3) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Drueckler3DDrucke`.`Models`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Drueckler3DDrucke`.`Models` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `fileName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Drueckler3DDrucke`.`PrintSettings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Drueckler3DDrucke`.`PrintSettings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `resolution` DECIMAL(3,2) NOT NULL,
  `infill` DECIMAL(3,2) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Drueckler3DDrucke`.`PrintConfig`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Drueckler3DDrucke`.`PrintConfig` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `Filaments_id` INT NOT NULL,
  `Models_id` INT NOT NULL,
  `PrintSettings_id` INT NOT NULL,
  `Orders_id` INT NOT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_GCodeFile_Filaments1_idx` (`Filaments_id` ASC),
  INDEX `fk_GCodeFile_Models1_idx` (`Models_id` ASC),
  INDEX `fk_GCodeFile_PrintSettings1_idx` (`PrintSettings_id` ASC),
  INDEX `fk_PrintConfig_Orders1_idx` (`Orders_id` ASC),
  CONSTRAINT `fk_GCodeFile_Filaments1`
    FOREIGN KEY (`Filaments_id`)
    REFERENCES `Drueckler3DDrucke`.`Filaments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GCodeFile_Models1`
    FOREIGN KEY (`Models_id`)
    REFERENCES `Drueckler3DDrucke`.`Models` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GCodeFile_PrintSettings1`
    FOREIGN KEY (`PrintSettings_id`)
    REFERENCES `Drueckler3DDrucke`.`PrintSettings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PrintConfig_Orders1`
    FOREIGN KEY (`Orders_id`)
    REFERENCES `Drueckler3DDrucke`.`Orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Drueckler3DDrucke`.`Pricing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Drueckler3DDrucke`.`Pricing` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `shiping` DECIMAL(6,2) NOT NULL,
  `workPerHour` DECIMAL(6,3) NOT NULL,
  `energyPerHour` DECIMAL(6,3) NOT NULL,
  `taxes` DECIMAL(4,2) NULL,
  `country` VARCHAR(50) NULL,
  PRIMARY KEY (`id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
